global:
  scrape_interval: 15s
  scrape_timeout: 15s


scrape_configs:
  - job_name: promethus
    metrics_path: /metrics
    static_configs:
      - targets: ['localhost:9090']
  
  - job_name: node-app
    scrape_interval: 5s
    metrics_path: /metrics
    static_configs:
      - targets: ['node_app:4000']
    
      
  
